version: '3.4'

services:
  backend:
    build: ./backend
    environment:
      - SECRET=supersecretsecretsyay
      - MONGODB=mongodb://root:welcome@mongo:27017/signin?authSource=admin
  frontend:
    build: 
      context: ./frontend
      args:
        - VUE_APP_API_URL="dockerfile"
  nginx:
    build: ./nginx
    ports: 
      - "80:80"
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: welcome
    volumes:
      - mongo_files:/data/db
volumes:
  mongo_files: