version: '3.4'

services:
  backend:
    build: ./backend
    environment:
      - SECRET=$SECRET
      - MONGODB=$MONGODB
      - clientId=$clientID
      - clientSecret=$clientSecret
      - BACKEND_URL=$BACKEND_URL
      - FRONTEND_URL=$FRONTEND_URL
  frontend:
    build: 
      context: ./frontend
      args:
        - VUE_APP_API_URL=$BACKEND_URL
  nginx:
    build: ./nginx
    ports: 
      - "80:80"
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongo_files:/data/db
volumes:
  mongo_files: